#!bin/bash

#!bin/bash

###This is a lightweight version of a vuln scanner. It is meant to inventory an environment. This will be the first step of monitoring the environment. All I have to do after inventorying the environment is comparing to previous inventories for changes


#the primary tool is nmap

##################################################start

#update tools used

sudo apt -y update

sudo apt -y upgrade nmap

sudo nmap --script-updatedb

# grab first three octets of network we are in

First_Three=$(ifconfig | grep netmask | awk '/broadcast/ {print $2}' | cut -d "." -f 1,2,3 | uniq)

# grab netmask of network

Net=$(ip addr show | grep inet | grep brd | tr '/' ' ' | awk '{print $3}')


#use these to run network scan with nmap

sudo nmap $First_Three.0/$Net > scan.txt



#############################################################################
#
#
#As you can see, it did everything up to the first scan of the vuln scanner
#The vuln scanner is meant to run once per day. this one is meant to run once per hour.
#I still haven't gotten around to comparing previous IPs to current IPs
#or putting a date and time into the name of a document
#or being able to retrieve a document with a unique date and time to compare to a whitelist
#or sending emails or texts to myself to alert myself to a change in network inventory
#
#
##############################################################################
