#!/bin/bash

#this is secure1host simplified. 

#it takes the same intent as the original secure1host but it simplifies it.

#the original secure1host was trying to do too much and it made it monolithic and awkward

#The origional secure1host tried too hard to be interactive, when all we want is something that makes a great one-liner and that is easy to use.

#what I want it to do is ask all of the questions at once and then - with one yes or no - do it all very quickly. Spacing out the questions is very annoying.

#then after that I want it to assess the security of the system after the configurations and give further suggestions using lynis.

#forget interactive and auto mode, just let it do its thing.


################################################################# args and variables

ARGS=$(getopt --options 'hycu' --long "help, yes, configure, user-settings" -- "$@")

set -- "$ARGS"

#config file path
path=/home/$(who | awk '/tty/ {print $1}')/Desktop/secure1host.config

All_Yes='n'
U_Settings='n'
C_Settings='n'

S_Update='n'
T_Update='n'
C_Update='n'
F_Default='n'
Net_Scan='n'
F_White_Port='n'
port=' '
Hard_Audit='n'
Log_Enable='n'
Hash='n'
Vuln_Scan='n'
Mon_Scan='n'
U_White='n'
U_Mon='n'
Scan_Detect='n'
Honey_Ports='n'
Scan_Frag='n'
Scan_Resp='n'
Auto_Response='n'


######################################################## Functions

Full_System_Update() { #Function Included

	if [ $S_Update == 'y' ]; then 
		echo "Beginning full system upgrade"
		echo " "
		sudo apt -y update
		sudo apt -y full-upgrade
		sudo apt -y autoremove
		sudo apt -y autoclean
		echo "System fully upgraded"
		echo " "

	fi
		
}

Tools_Update() { #Function Included

	if [ $T_Update == 'y' ]; then
		
		echo "Beginning tools update"
		echo " "
		sudo apt -y update
		sudo apt -y install nmap ufw lynis crontab
		sudo apt -y upgrade nmap ufw lynis crontab
		sudo apt -y autoremove
		sudo apt -y autoclean
		echo "tools fully installed and updated"
		echo " "
		
	fi

		
}

Auto_System_Updates() {  #function good
	
	if [ $C_Update == 'y' ]; then
		echo "0 1 * * * apt -y update 
1 1 * * * apt -y upgrade 
2 1 * * * apt -y autoremove 
3 1 * * * apt -y autoclean " | sudo crontab -
	fi


}


Default_Firewall_Enable() {

	if [ $F_Default == 'y' ]; then
		sudo ufw enable
	fi


}



Firewall_Whitelist_Single_Out_Port() {

	if [ $F_White_Port == 'y' ]; then
		sudo ufw allow out $port
		if [ $Flip_white_port == 'false' ]; then
			sudo ufw default deny outgoing
			Flip_white_port='true'
		fi
		Display_Firewall_Status
	fi
	


}




##################################STOP INCLUDING Here

Enable_Logging() {

	if [ $Log_Enable == 'y' ]; then
		echo 'not made yet'
		#do one thing
	fi


}

Scanning_Self_For_Vulnerabilities() {
	
	if [ $Vuln_Scan == 'y' ]; then
		echo 'not made yet'
	fi

	
}



Set_up_Netcat_scan_detector() {

	if [ $Scan_Detect == 'y' ]; then
		echo 'not made yet'
	fi

	
}

Monitoring_Neighbors() {

	if [ $Mon_Scan == 'y' ]; then
		echo 'not made yet'
	fi

	
}

Hashing_Files_and_Executables() {

	if [ $Hash == 'y' ]; then
		echo 'not made yet'
	fi

	
}


User_Whitelisting() {

	if [ $U_White == 'y' ]; then
		echo 'not made yet'
	fi

	
}

User_Monitoring() {

	if [ $U_Mon == 'y' ]; then
		echo 'not made yet'
	fi

	
}


Enable_Honey_Ports() {

	if [ $Honey_Ports == 'y' ]; then
		echo 'not made yet'
	fi

	
}


Frustrate_Scanning_Efforts() {

	if [ $Scan_Frag == 'y' ]; then
		echo 'not made yet'
	fi

	
}


Respond_To_Scanning() {

	if [ $Scan_Resp == 'y' ]; then
		echo 'not made yet'
	fi

	
}

Automated_Response() {

	if [ $Auto_Response == 'y' ]; then
		echo 'not made yet'
		#do one thing
	fi


}

###################################################progress report functions below


Display_Crontab() { #Function Included


	echo "---Displaying user crontab---"
	echo " "
	crontab -l
	echo " "
	echo "---Displaying root crontab---"
	echo " "
	sudo crontab -l
	echo " "


}

Display_Firewall_Status() { #function included

	echo "---Displaying UFW Firewall status---"
	echo " "
	sudo ufw status verbose
	echo " "

}

Basic_Net_Scan() {
	
	if [ $Net_Scan == 'y' ]; then
		echo "---Initiating basic network scan---"
		echo " "
		First_Three=$(ifconfig | grep netmask | awk '/broadcast/ {print $2}' | cut -d "." -f 1,2,3 | uniq)
		Net=$(ip addr show | grep inet | grep brd | tr '/' ' ' | awk '{print $3}')
		ID=$(ifconfig | grep netmask | awk '/broadcast/ {print $4}' | tr '.' ' ' | awk '{print $4}')
		sudo nmap -T4 $First_Three.$ID/$Net
		echo " "
	fi

	
}

Lynis_Hardening_Audit() {

	if [ $Hard_Audit == 'y' ]; then
		echo 'system will now do an internal audit'
		sudo lynis audit system
	fi
	
}

Progress_Report() {

		Display_Crontab
		Display_Firewall_Status
		Basic_Net_Scan
		Lynis_Hardening_Audit

}

####################################################### Checks and Help



Root_Check() { #good

	user=$(whoami)
	if [ $user != root ]; then
		echo 'Permission denied.'
		echo ' '
		Help
		exit
	fi

}

Help() { #good
	
	echo 'Displaying help:'
	echo ' '
	echo 'to run the program, execute "sudo secure1host"'
	echo 'to run the program with all settings enabled, execute "sudo secure1host -y" (or --yes)'
	echo 'to set up a configuration file, run "sudo secure1host -c" (or configure)'
	echo 'to run with a configuration file, run "sudo secure1host -u" (or user-settings)'
	echo 'to display this help again, run "secure1host -h (or --help)"'

}

############################################################## Set Variables

Set_Variables() {

	echo "Answer the following questions."
	echo " "
	echo "would you like to run a full upgrade of the system?(y/n)"
	read S_Update
	echo " "
	echo "would you like to install and update all tools used in this script?(y/n)"
	read T_Update
	echo " "
	echo "Would you like to create a cron job to run an upgrade of the system at 1AM every morning to protect it from vulnerabilities?(y/n)"
	read C_Update
	echo " "
	echo "Would you like to enable a default system firewall? (deny incoming, allow outgoing)(y/n)"
	read F_Default
	echo " "
	echo "Would you like to run a local subnet scan after the script runs?(y/n)"
	read Net_Scan
	echo " "
	echo "Would you like to run a System Hardening Audit after the script runs?(y/n)"
	read Hard_Audit
	echo " "

} 

############################################################## Run Commands

Run_Commands() {

	Full_System_Update
	Tools_Update
	Auto_System_Updates
	Default_Firewall_Enable

}

############################################################## All Yeses
All_Yes() {

	S_Update='y'
	T_Update='y'
	C_Update='y'
	F_Default='y'
	Net_Scan='y'
	F_White_Port='y'
	port=' '
	Hard_Audit='y'
	Log_Enable='y'
	Hash='y'
	Vuln_Scan='y'
	Mon_Scan='y'
	U_White='y'
	U_Mon='y'
	Scan_Detect='y'
	Honey_Ports='y'
	Scan_Frag='y'
	Scan_Resp='y'
	Auto_Response='y'
	
}

############################################################## Configure settings
Configure_Settings() {

	Set_Variables
	
	
	
	echo "S_Update=$S_Update" > $path
	echo "T_Update=$T_Update" >> $path
	echo "C_Update=$C_Update" >> $path
	echo "F_Default=$F_Default" >> $path
	echo "Net_Scan=$Net_Scan" >> $path
	echo "F_White_Port=$F_White_Port" >> $path
	echo "port=" >> $path
	echo "Hard_Audit=$Hard_Audit" >> $path
	echo "Log_Enable=$Log_Enable" >> $path
	echo "Hash=$Hash" >> $path
	echo "Vuln_Scan=$Vuln_Scan" >> $path
	echo "Mon_Scan=$Mon_Scan" >> $path
	echo "U_White=$U_White" >> $path
	echo "U_Mon=$U_Mon" >> $path
	echo "Scan_Detect=$Scan_Detect" >> $path
	echo "Honey_Ports=$Honey_Ports" >> $path
	echo "Scan_Frag=$Scan_Frag" >> $path
	echo "Scan_Resp=$Scan_Resp" >> $path
	echo "Auto_Response=$Auto_Response" >> $path


}

############################################################## Main

Main() {


	#changes settings based on options
	
	echo "Welcome to secure1host!"

	
	for i in $ARGS; do
		case "$i" in
			-h | --help)
				Help
				exit;;
			-y | --yes)
				All_Yes='y'
				shift;;
			-c | --configure)
				C_Settings='y'
				shift;;
			-u | --user-settings)
				U_Settings='y'
				shift;;
			--)
				echo " "
				Root_Check
				break;;

		esac
	done
	
	#executes based on settings
	
	if [ $All_Yes == 'y' ]; then
		All_Yes
	elif [ $U_Settings == 'y' ]; then
		source $path
		break
	elif [ $C_Settings == 'y' ]; then
		Configure_Settings
		echo 'configuration complete'
		echo 'run "sudo secure1host -u" to run with configurations'
		exit
	else
		Set_Variables
	fi
	
	Run_Commands
	Progress_Report
	
	echo "secure1host complete. Terminating script."
	exit
}

Main
